services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Containerfile
    expose:
      - 5432
    ports:
      - "127.0.0.1:5442:5432"
    volumes:
      - "./postgres/postgresql.conf:/etc/postgres/postgresql.conf"
      - "./postgres/init:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 1s
      retries: 5
