FROM docker.io/library/postgres:latest

# GHA service containers don't have access to the repository so we have to bake
# this in (unless we want to start the services manually in steps).
COPY postgresql.conf /etc/postgres/postgresql.conf
COPY init/ /docker-entrypoint-initdb.d/

# Custom entrypoint wrapping the upstream so we can inject debug prints.
COPY --chmod=755 entrypoint.sh /usr/local/bin
ENTRYPOINT ["entrypoint.sh"]

# Github Actions workflows can't give command to service container so
# we have to bake it into our own image.
# https://github.com/orgs/community/discussions/52675
CMD ["postgres", "-c", "config_file=/etc/postgres/postgresql.conf"]
