name: code-golf

include:
  - path: claude/compose-sub.yaml
    project_directory: .

  - path: containers/compose-sub.yaml
    project_directory: .

  - path: hello-world/compose-sub.yaml
    project_directory: .
