services:
  producer-haskell-dev:
    build:
      context: ./
      dockerfile: haskell/Containerfile-dev
    userns_mode: "keep-id"
    network_mode: host
    volumes:
      - "./haskell:/home/user/mq:U"
    entrypoint: /bin/zsh

  producer-haskell:
    build:
      context: ./
      dockerfile: haskell/Containerfile
    network_mode: host
    entrypoint: stack run
