# vi: ft=dockerfile
ARG registry=localhost
ARG tag=latest
FROM ${registry}/code-golf_message-queue_base-haskell:${tag}

USER root
RUN apt-get install -y libpq-dev libghc-zlib-dev
# libpq-dev required by postgres-simple
# libghc-zlib-dev required by http-client (zlib)

USER user
# Note the snapshot of stack.yml here must match the one from dummy
# Add a check later
# Note: podman-build can mount a volume, however, it does not accept --userns=keep-id so the
# permissions gets messed up
COPY --chown=user \
  message-queue/haskell/jmcgmqp.cabal \
  message-queue/haskell/stack.yaml \
  mq/
RUN cd mq && stack build --only-dependencies --trace

COPY --chown=user ../help.mk /home/
COPY --chown=user message-queue/mqp-base.mk /home/user/
WORKDIR mq
