FROM localhost/base-haskell

USER root
RUN apt-get install -y libpq-dev libghc-zlib-dev
# libpq-dev required by postgres-simple
# libghc-zlib-dev required by http-client (zlib)

USER user
# Note the snapshot of stack.yml here must match the one from dummy
# Add a check later
# Note: podman-build can mount a volume, however, it does not accept --userns=keep-id so the
# permissions gets messed up
COPY --chown=user jmcgmqp.cabal stack.yaml mq/
RUN cd mq && stack build --only-dependencies

WORKDIR mq
COPY --chown=user ./ ./
