FROM docker.io/library/debian:trixie-slim

RUN <<EOF
set -eu
printf "APT::Install-Recommends \"0\";" \
  > /etc/apt/apt.conf.d/no-install-recommends

apt-get update -y
apt-get upgrade -y

apt-get install -y \
  ca-certificates \
  curl \
  dub \
  g++ \
  git \
  gnupg2 \
  iproute2 \
  make \
  libboost-dev \
  strace \
  zsh
EOF

RUN <<EOF
curl -fsSL https://jan-matejka.github.io/debian-ppa/install | sh
apt-get install -y \
  dram \
  jm-util
EOF

RUN <<EOF
set -e
rm -rf /var/cache/apt/* /var/lib/apt/*

useradd -m --shell /bin/zsh user
chsh -s /bin/zsh root

mkdir -p git/dotfiles
git clone -q https://github.com/jan-matejka/dotfiles-zsh.git git/dotfiles/zsh
make -C git/dotfiles/zsh install
make -C git/dotfiles/zsh install HOME=/home/user USER=user
EOF
