services:
  postgres:
    build:
      context: container/postgres
      dockerfile: Containerfile
    expose:
      - 5432
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "./container/postgres/postgresql.conf:/etc/postgres/postgresql.conf"
      - "./container/postgres/init:/docker-entrypoint-initdb.d/"
    command: -c 'config_file=/etc/postgres/postgresql.conf'
