FROM docker.io/library/postgres:latest

# Github Actions workflows can't give command to service container so
# we have to bake it into our own image.
# https://github.com/orgs/community/discussions/52675
CMD postgres -c 'config_file=/etc/postgres/postgresql.conf'
