name: Build and push container image
description: with layer caching
inputs:
  image:
    required: true
    description: image name to build with podman-compose
  dir:
    required: true
    description: directory to call podman-compose in
  repository:
    description: git repository name
    default: code-golf
  registry:
    description: registry
    default: ghcr.io/${{ github.repository_owner }}
  registry_user:
    description: registry user
    default: ${{ github.actor }}
  registry_pass:
    description: registry password
    required: true
  base_tag:
    description: Base tag defining what version of the FROM image we build on
    required:
    default:
  no_cache:
    description: Build the image without layer cache
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Install podman-compose
      run: pip3 install podman-compose
      shell: sh
      # Ubuntu also uses too old (1.0.6) version
      #  run: sudo apt-get install -y podman-compose

    - name: Log in to the Github Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_user }}
        password: ${{ inputs.registry_pass }}

    - id: branch-tag
      name: Sanitize ref_name into a valid tag token
      env:
        ref_name: ${{ github.ref_name }}
      run: |
        echo "branch_tag=$ref_name" | sed 's#/#__#g' >> "${GITHUB_ENV}"
        echo "branch_tag=$ref_name" | sed 's#/#__#g' >> "${GITHUB_OUTPUT}"
      shell: sh

    - name: Build image
      env:
        IMAGE_FULL: >-
          ${{ inputs.repository }}_${{ inputs.dir }}_${{ inputs.image }}
        CACHE: >-
          ${{ inputs.registry }}/${{ inputs.repository }}_${{ inputs.dir }}_${{ inputs.image }}
        DIR: ${{ inputs.dir }}
        BASE_TAG: ${{ inputs.base_tag }}
        REPO: ${{ inputs.repository }}
        SHA: ${{ github.sha }}
        REGISTRY: ${{ inputs.registry }}
        IMAGE: ${{ inputs.image }}
      run: >
        set -x && cd $DIR &&
        extra="";
        [ -n "${{ inputs.base_tag }}" ] && {
          extra="--build-arg tag=$BASE_TAG"
        };
        [ "${{ inputs.no_cache }}" = "true" ] && {
          extra="$extra --no-cache"
        };
        podman-compose
        -p "${REPO}_${DIR}"
        --podman-build-args "
        -t ${IMAGE_FULL}:$SHA
        -t ${IMAGE_FULL}:$branch_tag
        --cache-from=${CACHE}
        --cache-to=${CACHE}"
        build
        $extra
        --build-arg registry=${REGISTRY}
        "${IMAGE}"
      shell: sh

    - name: Push image
      id: push
      uses: redhat-actions/push-to-registry@v2
      env:
        IMAGE_FULL: >
          ${{ inputs.repository }}_${{ inputs.dir }}_${{ inputs.image }}
      with:
        image: ${{ env.IMAGE_FULL }}
        tags: ${{ github.sha }} ${{ env.branch_tag }}
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_user }}
        password: ${{ inputs.registry_pass }}

    - name: Print image url
      env:
        paths: ${{ steps.push.outputs.registry-paths }}
      run: >
        printf "Image pushed to %s\n"
        "${PATHS}"
      shell: sh
