# vi: ft=dockerfile
ARG registry=localhost
ARG tag=latest
FROM ${registry}/code-golf_message-queue_base-debian-testing:${tag}

USER root
RUN apt-get install -y openssl rust-all

USER user
COPY --chown=user ../help.mk /home/
COPY --chown=user message-queue/mqp-base.mk /home/user/
COPY --chown=user message-queue/rust/Cargo.toml mq/

RUN cd mq && cargo fetch
RUN mkdir -p mq/src/lib mq/src/bin && \
  echo '// dummy' >> mq/src/lib/lib.rs && \
  echo 'fn main() {}' >> mq/src/bin/main.rs
RUN cd mq && cargo build

WORKDIR mq
