include:
  - path: pushgateway/compose.yaml
    project_directory: .
  - path: prometheus/compose.yaml
    project_directory: .
  - path: postgres/compose.yaml
    project_directory: .
  - path: postgres-test/compose.yaml
    project_directory: .

services:
  all:
    # dummy container via which we can refer to the group of containers
    # that provide the infrastructure to run producers against.
    image: ghcr.io/linuxcontainers/debian-slim:12
    command: /bin/sh -c 'while true; do sleep 1h; done'
    stop_signal: SIGKILL
    depends_on:
      - postgres
      - postgres-test
      - prometheus
      - pushgateway
