services:
  hello-world-haskell:
    build:
      context: ./
      dockerfile: hello-world/haskell/Containerfile
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./hello-world/haskell/:/app
      - ./common.mk:/common.mk
    userns_mode: "keep-id:uid=1000,gid=1000"
