ARG registry=localhost
ARG tag=latest
FROM ${registry}/code-golf_message-queue_base-debian:${tag}
# Base image with haskell tooling

RUN apt-get install -y \
  ghc haskell-stack cabal-install
# https://docs.haskellstack.org/en/stable/install_and_upgrade/#__tabbed_8_2
RUN stack upgrade --binary-only

USER user
WORKDIR /home/user/

# Note: stack setup takes a while as it downloads and compiles ghc
RUN stack setup

# Update the package index.
# This takes a while so run it separately in case the next command fails.
RUN stack update

RUN stack new dummy
# RUN cd dummy && stack install --allow-newer hfmt
# hfmt does not build due to
# `Distribution.PackageDescription.Parsec' does not export `readGenericPackageDescription
# RUN cd dummy && stack install --allow-newer hfmt
# hlint also does not build.
# cba to deal with this now.
