services:
  producer-golang-dev:
    build:
      context: ./
      dockerfile: golang/Containerfile-dev
    userns_mode: "keep-id"
    network_mode: host
    volumes:
      - "./golang:/home/user/mq:U"
    entrypoint: /bin/zsh

  producer-golang:
    build:
      context: ./
      dockerfile: golang/Containerfile
    network_mode: host
    entrypoint: /home/user/mq/main
