# vi: ft=dockerfile
ARG registry=localhost
ARG tag=latest
FROM ${registry}/code-golf_message-queue_base-debian:${tag}

RUN apt-get install -y \
  golang

USER user
COPY --chown=user ../mqp-base.mk /home/user/
COPY --chown=user golang/src/go.mod golang/src/go.sum /home/user/mq/src/

WORKDIR mq
RUN cd src && echo 'package jmcgmqp' >config.go && go get -t -x ./
