include:
  - path: container/base-debian/compose.yaml
    project_directory: .
  - path: container/base-debian-testing/compose.yaml
    project_directory: .
  - path: container/base-haskell/compose.yaml
    project_directory: .
  - path: container/grafana/compose.yaml
    project_directory: .
  - path: container/postgres/compose.yaml
    project_directory: .
  - path: container/postgres-prometheus-exporter/compose.yaml
    project_directory: .
  - path: container/postgres-test/compose.yaml
    project_directory: .
  - path: cpp/compose.yaml
    project_directory: .
  - path: golang/compose.yaml
    project_directory: .
  - path: rust/compose.yaml
    project_directory: .
  - path: python/compose.yaml
    project_directory: .
  - path: haskell/compose.yaml
    project_directory: .

services:
  infra:
    # dummy container via which we can refer to the group of containers
    # that provide the infrastructure to run producers against.
    image: ghcr.io/linuxcontainers/debian-slim:12
    command: /bin/sh -c 'while true; do sleep 1h; done'
    stop_signal: SIGKILL
    depends_on:
      - grafana
      - postgres
      - postgres-test
      - postgres-prometheus-exporter
