x-podman:
  in_pod: False

include:
  - container/base-debian/compose.yaml
  - container/base-debian-testing/compose.yaml
  - container/base-haskell/compose.yaml
  - container/grafana/compose.yaml
  - container/postgres/compose.yaml
  - container/postgres-prometheus-exporter/compose.yaml
  - container/postgres-test/compose.yaml
  - container/prometheus/compose.yaml
  - container/pushgateway/compose.yaml
  - cpp/compose.yaml
  - golang/compose.yaml
  - rust/compose.yaml
  - python/compose.yaml
  - haskell/compose.yaml
  - ../telemetry/postgres/compose.yaml

services:
  infra:
    # dummy container via which we can refer to the group of containers
    # that provide the infrastructure to run producers against.
    image: ghcr.io/linuxcontainers/debian-slim:12
    command: /bin/sh -c 'while true; do sleep 1h; done'
    stop_signal: SIGKILL
    depends_on:
      - grafana
      - postgres
      - postgres-test
      - telemetry-postgres
      - prometheus
      - pushgateway
      - postgres-prometheus-exporter
