services:
  producer-cpp-dev:
    build:
      context: ../
      dockerfile: message-queue/cpp/Containerfile-dev
    userns_mode: "keep-id"
    network_mode: host
    volumes:
      - "./cpp:/home/user/mq:U"
    entrypoint: /bin/zsh

  producer-cpp:
    build:
      context: ./
      dockerfile: cpp/Containerfile
    network_mode: host
    entrypoint: /home/user/mq/main
