# vi: ft=dockerfile

ARG registry=localhost
ARG tag=latest
FROM ${registry}/code-golf_message-queue_base-debian:${tag}

RUN apt-get install -y \
  prometheus-cpp-dev libgtest-dev libboost-dev libpqxx-dev libfmt-dev

USER user
COPY --chown=user ../mqp-base.mk /home/user/
WORKDIR mq
