# vi: ft=dockerfile

ARG registry=localhost
ARG tag=latest
FROM ${registry}/code-golf_message-queue_base-debian:${tag}

RUN apt-get install -y \
  prometheus-cpp-dev libgtest-dev libboost-dev libpqxx-dev libfmt-dev \
  cppcheck

USER user
COPY --chown=user ../help.mk /home/
COPY --chown=user message-queue/mqp-base.mk /home/user/
WORKDIR mq
