# vi: ft=dockerfile

FROM localhost/message-queue_base-debian

RUN apt-get install -y \
  prometheus-cpp-dev libgtest-dev libboost-dev libpqxx-dev

USER user
COPY --chown=user ../mqp-base.mk /home/user/
WORKDIR mq
