services:
  hello-world-sh:
    build:
      context: ./
      dockerfile: hello-world/sh/Containerfile
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./hello-world/sh/:/app
      - ./common.mk:/common.mk
    x-podman.uidmaps:
      - +1000:@1000
