FROM localhost/base-debian

RUN apt-get install -y python3 python3-venv

COPY --chown=user setup.py mq/
COPY --chown=user src/jmcgmqp/__init__.py mq/src/jmcgmqp/

RUN set -e;\
  python3 -m venv venv;\
  . venv/bin/activate;\
  cd mq;\
  ls;\
  pip install -e ./

COPY --chown=user container/zshrc /home/user/.zshrc2
COPY --chown=user ./ mq/
WORKDIR mq
