services:
  hello-world-c:
    build:
      context: ./
      dockerfile: hello-world/c/Containerfile
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./hello-world/c/:/app
      - ./common.mk:/common.mk
    userns_mode: "keep-id:uid=1000,gid=1000"
