ARG REGISTRY=localhost
ARG BASE_IMAGE_TAG=latest
ARG COMPOSE_PROJECT_NAME
ARG BASE_IMAGE_NAME=debian

ENV BASE_MK=/base.mk

FROM ${REGISTRY}/${COMPOSE_PROJECT_NAME}_${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

COPY --chown=user hello-world/c/ /app
COPY --chown=user hello-world/test/ /test
COPY --chown=user base.mk /base.mk

WORKDIR /app
RUN make

USER user
CMD ["zsh"]
