services:
  postgres-test:
    image: postgres
    expose:
      - 5432
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "./container/postgres-test/postgresql.conf:/etc/postgres/postgresql.conf"
      - "./container/postgres/init:/docker-entrypoint-initdb.d/"
      - type: tmpfs
        target: /var/lib/postgresql
