services:
  postgres-test:
    build:
      context: container/postgres
      dockerfile: Containerfile
    expose:
      - 5433
    ports:
      - "127.0.0.1:5433:5433"
    volumes:
      - "./container/postgres-test/postgresql.conf:/etc/postgres/postgresql.conf"
      - "./container/postgres/init:/docker-entrypoint-initdb.d/"
      - type: tmpfs
        target: /var/lib/postgresql
    command: -c 'config_file=/etc/postgres/postgresql.conf'
