name: message-queue CI

on:
  push:
    paths:
      - "message-queue/**"
      - ".github/**"

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-base-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: base-debian
          dir: message-queue
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}

  build-base-debian-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: base-debian-testing
          dir: message-queue
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
