name: message-queue CI

on:
  push:
    paths:
      - "message-queue/**"
      - ".github/**"

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common:
    if: true
    uses: ./.github/workflows/mq-infra.yaml
    secrets: inherit
