name: message-queue haskell CI

on:
  push:
    paths:
      - "message-queue/**"
      - ".github/**"

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common:
    if: true
    uses: ./.github/workflows/mq-infra.yaml
    secrets: inherit

  build-base-haskell:
    if: true
    needs: common
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: base-haskell
          dir: message-queue
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
          base: base-debian

  build-producer-haskell-dev:
    if: true
    needs: build-base-haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: producer-haskell-dev
          dir: message-queue
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
          base: base-haskell

  build-producer-haskell:
    if: true
    needs: build-producer-haskell-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: producer-haskell
          dir: message-queue
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
          base: producer-haskell-dev

  test-producer-haskell:
    if: true
    needs:
      - build-producer-haskell
      - common
    uses: ./.github/workflows/mq-run-test.yaml
    with:
      name: haskell
    secrets: inherit
