name: message-queue rust CI

on:
  push:
    paths:
      - "message-queue/**"
      - ".github/**"

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common:
    if: true
    uses: ./.github/workflows/mq-infra.yaml
    secrets: inherit

  build-base-debian-testing:
    if: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: base-debian-testing
          dir: message-queue
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}

  build-producer-rust-dev:
    if: true
    needs: build-base-debian-testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: producer-rust-dev
          dir: message-queue
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
          base: base-debian-testing

  build-producer-rust:
    if: true
    needs: build-producer-rust-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: producer-rust
          dir: message-queue
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
          base: producer-rust-dev

  test-producer-rust:
    if: true
    needs:
      - build-producer-rust
      - common
    uses: ./.github/workflows/mq-run-test.yaml
    with:
      name: rust
    secrets: inherit
